# Generated by Django 5.1.4 on 2025-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='fodmap_friendly',
            field=models.BooleanField(default=True),
        ),
    ]
