# Generated by Django 5.1.4 on 2025-08-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_seed_diet_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diet_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_types',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='recipes.diettype'),
        ),
    ]
