# Generated by Django 5.1.4 on 2025-10-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_dietprotocol_ingredient_tags_dietprotocolrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionrule',
            name='rule',
            field=models.CharField(choices=[('allow', 'Allow'), ('avoid', 'Avoid'), ('limit', 'Limit')], max_length=8),
        ),
        migrations.AlterField(
            model_name='restrictionrule',
            name='threshold',
            field=models.FloatField(blank=True, help_text='Per-serving limit for LIMIT rules', null=True),
        ),
    ]
